## Statistics Exercises

In [1]:
import numpy as np
import pandas as pd

### How likely is it that you roll doubles when rolling two dice?

In [35]:
# 1. Represent data 1-6
# 2. Create the matrix

dice_sample = pd.DataFrame(np.random.choice([1, 2, 3, 4, 5, 6], size=(1000, 2)))
dice_sample

0  1
0    5  6
1    5  4
2    2  6
3    4  6
4    6  3
..  .. ..
995  2  3
996  3  3
997  2  4
998  5  5
999  2  4

[1000 rows x 2 columns]

In [3]:
dice_sample[0] == dice_sample[1]

0       True
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [4]:
(dice_sample[0] == dice_sample[1]).mean()

0.165

### If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
# 1. Represent data -- 0 is tails, 1 is heads
# 2. Create the matrix

flips = np.random.choice([0,1], size=(10_000, 8))
flips

array([[1, 1, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 1, 1]])

In [6]:
simulation_results = flips.sum(axis=1)
simulation_results

array([5, 6, 4, ..., 3, 5, 7])

In [7]:
(simulation_results == 3).mean()

0.217

In [8]:
(simulation_results > 3).mean()

0.6386

### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [39]:
# 1. Represent data 1 = DS, 0 = WD
# 2. Create the matrix
n_rows = 10_000
n_cols = 2

cohorts = np.random.choice([1, 0, 0, 0], n_rows * n_cols).reshape(n_rows, n_cols)
cohorts

array([[1, 1],
       [0, 1],
       [0, 0],
       ...,
       [0, 1],
       [0, 0],
       [1, 0]])

In [40]:
billboards_2_ds = ((cohorts.sum(axis = 1) == 2).mean())
billboards_2_ds

0.0689

### Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [77]:
# 1. Represent data 
# 2. Create the matrix
poptarts = np.random.normal(3, 1.5, (1000000,5))
poptarts = np.where(poptarts < 0, 0, poptarts)
purchase_poptarts = poptarts.round(0)
purchase_poptarts

array([[3., 1., 5., 1., 3.],
       [3., 4., 5., 4., 4.],
       [2., 2., 3., 0., 4.],
       ...,
       [4., 5., 4., 4., 0.],
       [3., 5., 3., 3., 7.],
       [4., 6., 4., 2., 3.]])

In [96]:
poptarts_left = ((purchased_poptarts.sum(1) <= 16).mean())
poptarts_left

0.670521

### Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- If a man and woman are chosen at random, P(woman taller than man)?

In [41]:
# 1. Represent data
# 2. Create the matrix

men = np.random.normal(178, 8, 100_000)
women = np.random.normal(170, 6, 100_000)
woman_taller = (women > men).mean()
woman_taller

0.21311

### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

### How likely is it that 450 students all download anaconda without an issue?

In [141]:
# 1. Represent data
# 2. Create the matrix

n_rows = 10_000

def anaconda_installs(trials):
    return np.random.choice(249 * [False]  + [True], (n_rows, trials))

In [142]:
trials_50 = anaconda_installs(50)
trials_50.sum(axis = 1)

array([0, 0, 0, ..., 0, 0, 0])

In [143]:
(trials_50.sum(axis = 1) == 0).mean()

0.8206

In [144]:
trials_100 = anaconda_installs(100)
trials_100.sum(axis = 1)

array([2, 0, 0, ..., 0, 0, 2])

In [145]:
1 - (trials_100.sum(axis = 1) == 0).mean()

0.3355

In [146]:
trials_450 = anaconda_installs(450)
trials_450.sum(axis = 1)

array([1, 1, 1, ..., 3, 1, 2])

In [147]:
(trials_450.sum(axis = 1) == 0).mean()

0.1689

### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

### How likely is it that a food truck will show up sometime this week?

In [123]:
# 1. Represent data
# 2. Create the matrix

days = np.random.choice([0 ,1], size=(10_000, 3), p=(.3, .7))
days

array([[0, 1, 0],
       [1, 1, 1],
       [1, 0, 1],
       ...,
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [124]:
(days.sum(axis = 1) == 0).mean()

0.0285

### If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [160]:
# 1. Represent data
# 2. Create the matrix

random_23_birthdays = np.random.randint(0,366,(10_000,23))
random_23_birthdays

array([[315, 349, 342, ..., 282,  90, 176],
       [ 61, 275, 167, ...,  48,  36, 132],
       [182, 324, 306, ..., 235, 207,  88],
       ...,
       [312,  75, 166, ..., 156, 236, 133],
       [321, 317, 104, ...,   9, 199, 263],
       [119, 265, 217, ..., 136, 131, 193]])

In [162]:
random_23 = pd.DataFrame(random_23_birthdays)
random_23

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     315  349  342  127  159  197    6  121  174  325  ...  336  364  338   
1      61  275  167  274   45  176  165  239    3  115  ...  222  302  164   
2     182  324  306  117  222  169   33  353   12  245  ...  203  263   21   
3     264  245  329  194  238  289  209   31  241  363  ...  256  295  302   
4     151  313  104  181   90  323  200   18  309  197  ...  206  235  290   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   15   21  187    5  287  167  242  113  166  129  ...  138   74   53   
9996  100  239  229   90  288   75   56  360   71  182  ...  272  146  109   
9997  312   75  166  275  251  264   61  359  152  163  ...  200  247  103   
9998  321  317  104  132   17  127    5  335  229  250  ...  271  284  126   
9999  119  265  217  247   88   34   53  296  335  304  ...  111  360   83   

       16   17   18   19   20   21   22  
0      98  152  182   65  282   90  176  
1      14  291  344  191   48   36  132  
2     286  155  251  260  235  207   88  
3     100  198  137   46  117  308  352  
4      45   88  134   31   41  355  286  
...   ...  ...  ...  ...  ...  ...  ...  
9995  178   21   62  113  141   58  218  
9996  234  242  241  228   46  316  127  
9997   94  115  289  178  156  236  133  
9998  227    8  181   91    9  199  263  
9999  181  365  350  216  136  131  193  

[10000 rows x 23 columns]

In [163]:
shared_birthdays_23 = random_23.apply(lambda x: len(set(x)) != len(x), axis=1).mean()
shared_birthdays_23

0.51

In [165]:
random_20_birthdays = np.random.randint(0,366,(10_000,20))
random_20_birthdays

array([[219, 276,   9, ...,  61, 193,  45],
       [ 82, 116, 246, ..., 310,  93, 267],
       [193, 124,  73, ...,  50,  39, 327],
       ...,
       [326, 267, 230, ..., 324, 295, 299],
       [345, 234, 343, ..., 244, 249, 266],
       [273,  50,   8, ..., 153, 253, 268]])

In [167]:
random_20 = pd.DataFrame(random_20_birthdays)
random_20

0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0     219  276    9  335  141  253  103   97  133  284  309  277   85   69   
1      82  116  246  151  156  109  109  243  275  258   53  208  348  312   
2     193  124   73   25   64  149  235   51  258  208  354  311   78  106   
3      41  235  252  248  350    3  138   43  243    6  244   27   84  188   
4     204   36  177  320  293  293  272  334  177   86  170  237  231  252   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  311   65  317  142  145  307  196   24  250  312  351  144  139  197   
9996  357  291   52  343  365  342  267  263  155  159  129  248  212  127   
9997  326  267  230   23  110  145   68   51  240   58  332  172  269  142   
9998  345  234  343   37   22   73    3  159   57  257  310  132  260    4   
9999  273   50    8  365   50  266   97    6  140   22  126  169  322  295   

       14   15   16   17   18   19  
0     300  300  348   61  193   45  
1      70  255  217  310   93  267  
2      20  128  123   50   39  327  
3     293  205   35  255  183  245  
4     338  195  154  306  346  255  
...   ...  ...  ...  ...  ...  ...  
9995  210  119  127   66   56  226  
9996  330  134  330    6  177  341  
9997   61  287  342  324  295  299  
9998  340  187  181  244  249  266  
9999  236   91  137  153  253  268  

[10000 rows x 20 columns]

In [169]:
shared_birthdays_20 = random_20.apply(lambda x: len(set(x)) != len(x), axis=1).mean()
shared_birthdays_20

0.4078

In [170]:
random_40_birthdays = np.random.randint(0,366,(10_000,40))
random_40_birthdays

array([[ 59,  15, 215, ..., 329, 256,  15],
       [ 82,  29, 163, ...,  23, 184, 216],
       [179, 147, 208, ...,  55, 283,   8],
       ...,
       [ 22, 347, 159, ..., 261,  25, 238],
       [331, 131,  24, ...,  87, 183,  54],
       [ 35,  75, 292, ..., 145, 114, 282]])

In [171]:
random_40 = pd.DataFrame(random_40_birthdays)
random_40

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0      59   15  215   98  289  101  312  147  136  155  ...  359  310  238   
1      82   29  163  253  154   78  204  107  186  298  ...   33  240  114   
2     179  147  208  161  141  146  194  177  326   10  ...  268  361   58   
3     272  277  277   55   41  197  236  108  172  356  ...  321  227  178   
4      15  149   38  259  198  276  235    0  265   65  ...  192  195   99   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  260   89  348  157  105  342  353  146  307  115  ...  258  292  147   
9996   16  260   98   98   22   64  192   55  185    4  ...  108  266  103   
9997   22  347  159   81   51  269  363  362  350  106  ...   13  346  144   
9998  331  131   24  140   17  355  297  119  326   81  ...  199  161   18   
9999   35   75  292  217  336    7  108  288  153  160  ...  298  219   68   

       33   34   35   36   37   38   39  
0     196   69   36  255  329  256   15  
1      29    8   16  205   23  184  216  
2     260  210  163   32   55  283    8  
3      15  285  238  283   54  127  137  
4     134  338  200   55  320  335  268  
...   ...  ...  ...  ...  ...  ...  ...  
9995  132   13  330  156   77  227   19  
9996  343  294  306  242  250   54  270  
9997  217  248  273  239  261   25  238  
9998  164   72   42   72   87  183   54  
9999  349   47   48   13  145  114  282  

[10000 rows x 40 columns]

In [172]:
shared_birthdays_40 = random_40.apply(lambda x: len(set(x)) != len(x), axis=1).mean()
shared_birthdays_40

0.8945