## Statistics Exercises

In [1]:
import numpy as np
import pandas as pd

### How likely is it that you roll doubles when rolling two dice?

In [35]:
# 1. Represent data 1-6
# 2. Create the matrix

dice_sample = pd.DataFrame(np.random.choice([1, 2, 3, 4, 5, 6], size=(1000, 2)))
dice_sample

0  1
0    5  6
1    5  4
2    2  6
3    4  6
4    6  3
..  .. ..
995  2  3
996  3  3
997  2  4
998  5  5
999  2  4

[1000 rows x 2 columns]

In [3]:
dice_sample[0] == dice_sample[1]

0       True
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [4]:
(dice_sample[0] == dice_sample[1]).mean()

0.165

### If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
# 1. Represent data -- 0 is tails, 1 is heads
# 2. Create the matrix

flips = np.random.choice([0,1], size=(10_000, 8))
flips

array([[1, 1, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 1, 1]])

In [6]:
simulation_results = flips.sum(axis=1)
simulation_results

array([5, 6, 4, ..., 3, 5, 7])

In [7]:
(simulation_results == 3).mean()

0.217

In [8]:
(simulation_results > 3).mean()

0.6386

### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [39]:
# 1. Represent data 1 = DS, 0 = WD
# 2. Create the matrix
n_rows = 10_000
n_cols = 2

cohorts = np.random.choice([1, 0, 0, 0], n_rows * n_cols).reshape(n_rows, n_cols)
cohorts

array([[1, 1],
       [0, 1],
       [0, 0],
       ...,
       [0, 1],
       [0, 0],
       [1, 0]])

In [40]:
billboards_2_ds = ((cohorts.sum(axis = 1) == 2).mean())
billboards_2_ds

0.0689

### Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [77]:
poptarts = np.random.normal(3, 1.5, (1000000,5))
poptarts = np.where(poptarts < 0, 0, poptarts)
purchase_poptarts = poptarts.round(0)
purchase_poptarts

array([[3., 1., 5., 1., 3.],
       [3., 4., 5., 4., 4.],
       [2., 2., 3., 0., 4.],
       ...,
       [4., 5., 4., 4., 0.],
       [3., 5., 3., 3., 7.],
       [4., 6., 4., 2., 3.]])

In [78]:
poptarts_left = ((purchased_poptarts.sum(1) <= 16).mean())
poptarts_left

0.670521

### Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- If a man and woman are chosen at random, P(woman taller than man)?

In [41]:
men = np.random.normal(178, 8, 100_000)
women = np.random.normal(170, 6, 100_000)
woman_taller = (women > men).mean()
woman_taller

0.21311

### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

### How likely is it that 450 students all download anaconda without an issue?